brew "bash"
brew "curl"
brew "git"
brew "vim"

brew "fish"
brew "go"
brew "node"
brew "python"
brew "ruby"

brew "cloc"
brew "fzf"
brew "hub"
brew "mas"
brew "shellcheck"
brew "trash"
brew "tree"
brew "unrar"
brew "xz"
brew "yarn"

brew "mpv"
brew "neovim"
brew "newsboat"
brew "tmux"

tap "caskroom/versions"
cask "alfred"
cask "betterzip"
cask "calibre"
cask "dropbox"
cask "google-chrome"
cask "google-chrome-canary"
cask "gpg-suite-nightly"
cask "mactex"
cask "parallels-desktop11"
cask "skim"
cask "spotify"
cask "sublime-text-dev"
cask "telegram"
cask "transmission"

# Quick Look plugins
# https://github.com/sindresorhus/quick-look-plugins
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-json"
cask "quicklookase"
cask "suspicious-package"
cask "webpquicklook"

mas "Bubble Translate", id: 986431962
mas "Tyme2", id: 1063996724
